version: 2.1
# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run