version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: aws iam list-users
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
