version: 2.1

# anchors
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

commands:
  simple_echo:
    description: echoes a message
    parameters:
      msg:
        type: string
        default: ""
    steps:
      - when:
          condition: << parameters.msg >>
          steps:
            - run: echo non-default << parameters.msg >>
      - unless:
          condition: << parameters.msg >>
          steps:
            - run: echo default

# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  save_output:
    <<: *defaults
    steps:
      - run: echo hello from $CIRCLE_JOB > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt
  read_output:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/output.txt
  print_url_with_command:
    <<: *defaults
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps:
      - simple_echo
      - simple_echo:
          msg: $CIRCLE_COMPARE_URL
      - run:
          name: If this fails, something is done
          command: echo shice
          when: on_fail
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  print_env:
    jobs:
      - print_url_with_command
  use_workspace:
    jobs:
      - save_output
      - read_output:
          requires: 
           - save_output