---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install node and npm"
  become: yes
  apt:
      name: [nodejs, npm]
      state: present
  register: installnpm_output

- debug:
    var: installnpm_output

- name: "install pm2"
  become: yes
  npm:
      name: pm2
      global: yes

- name: "create ~/web dir"
  file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy index.js"
  copy:
    src: files/index.js
    dest: ~/web

- name: "start web server"
  command: "pm2 start ~/web/index.js -f"

