# aws cloudformation create-stack --stack-name networking --template-body file://networking.yaml --parameters file://networking_params.json --region us-east-1
Description: >
  This is a template file that creates a database in the given VPC.

Parameters:
  EnvironmentName:
    Description: An environment name that will be used to prefix resource name
    Type: String
  dbUser:
    Type: String
  dbPassword:
    Type: String
AWSTemplateFormatVersion: 2010-09-09

Resources:
  DBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow port 3306 to the db
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for the RDS
      SubnetIds: 
        - Fn::ImportValue: !Sub ${EnvironmentName}-PRIV-NET1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PRIV-NET2
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      AllowMajorVersionUpgrade: True
      AutoMinorVersionUpgrade: True
      DBInstanceClass: db.t2.small
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeleteAutomatedBackups: True
      DeletionProtection: True
      Engine: mysql
      MasterUsername: !Sub "${dbUser}"
      MasterUserPassword: !Sub "${dbPassword}"
      Port: 3306
      VPCSecurityGroups: 
        - Ref: DBSecGroup
