# aws cloudformation create-stack --stack-name networking --template-body file://networking.yaml --parameters file://networking_params.json --region us-east-1
Description: >
  This is a template file that creates servers, an autoscaling group and a LB in the given VPC.

Parameters:
  EnvironmentName:
    Description: An environment name that will be used to prefix resource name
    Type: String
  Port:
    Description: The port of the application to serve from and the LB to route to
    Type: Number
  LBPort:
    Description: The port of the LB to listen to
    Type: Number
AWSTemplateFormatVersion: 2010-09-09

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our LB
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref LBPort
        ToPort: !Ref LBPort
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: !Ref LBPort
        ToPort: !Ref LBPort
        CidrIp: 0.0.0.0/0
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref Port
        ToPort: !Ref Port
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            cd /var/www/html
            echo “it works! Udagram, Udacity! Hostname: $(hostname -f)” > /var/www/html/index.html
        ImageId: ami-08e4e35cccc6189f4
        #KeyName: default
        SecurityGroupIds:
          - Ref: WebServerSecGroup
        InstanceType: t2.small
        BlockDeviceMappings:
        - DeviceName: /dev/sdk
          Ebs: 
            VolumeSize: 10
            VolumeType: gp2

  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub "${EnvironmentName}-PRIV-NETS"
      LaunchTemplate:
        LaunchTemplateId: !Ref WebAppLaunchTemplate
        Version: !GetAtt WebAppLaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '3'
      TargetGroupARNs:
      - Ref: WebAppTargetGroup
      HealthCheckGracePeriod: 60
      HealthCheckType: ELB
  WebAppTargetGroup: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Port: !Ref Port
      Protocol: HTTP
      TargetType: instance
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      SecurityGroups: 
        - Ref: LBSecGroup
      Subnets: 
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-NET1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-NET2
  WebAppLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: !Ref LBPort
      Protocol: HTTP
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: 
          Ref: WebAppTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn:
        Ref: WebAppLBListener
      Priority: 1

Outputs:
  LoadBalancerDNS:
    Description: The URL to the Load Balancer
    Value: !Sub "http://${WebAppLB.DNSName}"
    Export:
      Name: !Sub ${EnvironmentName}-LoadBalancerDNS