AWSTemplateFormatVersion: 2010-09-09
Description: 'Mario H / Udacity - This template deploys a VPC'
Resources:
  UdacityVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: 'true'
      Tags:
      - Key: name
        Value: myfirsttestvpc